### ISSUE TITLE
Inject environment variables in Javascript Scope

### ISSUE THREAD

**Issue by jurekbarth** [biotope/biotope-build#110]
In order to develop against an API it would be helpful to have environment variables to get API Keys or the the API url.

An example:
```
const apiKey = process.env.API_KEY
const apiUrl = process.env.API_URL
```

**Comment by janrembold** [comment]
@jurekbarth Where do you want to inject this? At task start `yarn start`? And why not set it internally? If the environment variables are set outside you won't have any informations about that in the dist folder.

Usually we put those informations either in the front-matter YAML on top of the entry `page` HBS. Or this is set in scripts section in the head (biotope.configuration)

**Comment by jurekbarth** [comment]
I want to have an `.env` file that gets picked up on `yarn <command>`. While building the dist file it should replace these variables with the values specified in the `.env` file. 
HBS is not the right place, as i want to define these variables per environment and sometimes i don't even want to have them in the Repo. The configuration file is a workaround that could work, but i really want to *bake* the values in that file.
A good example could be the `ENVIRONTMENT` variable.  For extended logging and errors.

```
if(ENVIRONTMENT === 'develop') {
console.log(value)
}
```

Now the uglifier is smart enough to read the equation. If it's false it will just delete that code. --> Smaller bundle sizes.

**Comment by janrembold** [comment]
Thanks for the explanation, now I understand it a little bit better, but still have no clue what should be the advantage of doing it that way. IMO this just adds another dependency between the code, the build process and yet another config file called `.env`.

Your example with the API URL/Key perfectly fits in the currently used configuration.js. This file depends on the system it is used in and is usually only filled with demo data inside the repo. The "real" data is only available inside each environment.

The other example with conditional logging is interesting at first sight but I still don't like the idea of filling up our codes with console logs, even if they are kicked out at runtime (same additional dependency problem from above). I think this should better be solved with automated tests instead of conditional logging

**Comment by jurekbarth** [comment]
But then how would i change between environments, at build time?

**Comment by janrembold** [comment]
With "at build time" you mean that a resulting scripts.all.min.js includes for...

- ... Build A: `var test = 'A'`
- ... Build B: `var test = 'B'`

If that's true, this would be a bad practice in my eyes.
This should result in `var test = this.options.foo` where the option `foo` was injected from outside the plugin like:

```
var plugin = new SomePlugin({ foo: biotope.configuration.get('foo') })
```

**Comment by SheepFromHeaven** [comment]
As I understand you are speaking of different things:

Environment variables are a best practice in Node.js and surely it will change the compiled code in the build process. But I think @janrembold your example is very biased as this is a bad usecase for that.

For this case a configuration is the right way to go. But let's look at a configuration for an API for example. In development I want to include a mock api adapter which I never need in production.

I can then do something like this in JS

```
import MockApiAdapter from 'mock';
import LiveApiAdapter from 'live';

const apiAdapter = process.env.NODE_ENV === 'production' ? LiveApiAdapter : MockApiAdapter;
startApp(new apiAdapter());
```

If the NODE_ENV is then 'production' this will become an ever true statement and uglify will throw it out, as well as the unused import. This will result in a much smaller bundle size.

By doing this with the configuration.js, the configuration will be available at runtime (not needed code), it will bloat up the window object.

I hope this helps. Maybe also look here: https://gist.github.com/markerikson/6776848172c33aaa4db882627c689e18

**Comment by timomayer** [comment]
thanks marc helps your exmaple helps to understand the case. but i still do not see the usecase for having different adapters. can you describe a usecase?
in my oppinion the path will change between mock and live, (thats what we do with configuration) but not the whole adapter?

**Comment by SheepFromHeaven** [comment]
@timomayer we have the same usecase in one project where we programatically create an api response on the go in the frontend. So there never is a http request in development.

I don't think that this will happen all the time, but even exchanging only the url on buildtime is a reason for using environment variables. Just so we can have the smallest bundlesize possible.

**Comment by timomayer** [comment]
@SheepFromHeaven i am not sure if thats a practice we wanna use in our projects in general. why not having the exact same code for dev and production and use a mock file or mock server for development? how do you test the behaviour of the http request? you need to test it in production mode or you have to change your code to use it in development instead of the "direct api response"?
